# Generated by Django 4.1.5 on 2023-11-30 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='Relation_Tags',
        ),
        migrations.AddField(
            model_name='art_tags',
            name='arts_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='art', to='main.art'),
        ),
    ]
