# Generated by Django 4.1.5 on 2023-12-01 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_art_tags_arts_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Whatsapp', models.TextField(default='No Available', max_length=8)),
                ('Facebook', models.TextField(default='No Available', max_length=500)),
                ('Instagram', models.TextField(default='No Available', max_length=500)),
                ('Social_Owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
